-- =============================================================================
-- Migration 002 — Superadmin & Multi-Tenancy Hardening
-- Run this against your Supabase project SQL editor.
-- Safe to re-run: all statements are idempotent.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add 'superadmin' to the role CHECK constraint on public.users
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  con_name TEXT;
BEGIN
  -- Find the role check constraint name (auto-generated by Supabase)
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.users'::regclass
    AND contype   = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%role%';

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.users DROP CONSTRAINT %I', con_name);
  END IF;
END $$;

ALTER TABLE public.users
  ADD CONSTRAINT users_role_check
  CHECK (role IN ('student', 'teacher', 'admin', 'superadmin'));

-- Also update profiles table if it exists
DO $$
DECLARE
  con_name TEXT;
BEGIN
  SELECT conname INTO con_name
  FROM pg_constraint
  WHERE conrelid = 'public.profiles'::regclass
    AND contype   = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%role%';

  IF con_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT %I', con_name);
    ALTER TABLE public.profiles
      ADD CONSTRAINT profiles_role_check
      CHECK (role IN ('student', 'teacher', 'admin', 'superadmin'));
  END IF;
EXCEPTION WHEN undefined_table THEN
  NULL; -- profiles table doesn't exist, skip
END $$;

-- ---------------------------------------------------------------------------
-- 2. Add is_active flag to institutions (for soft-disable by superadmin)
-- ---------------------------------------------------------------------------
ALTER TABLE public.institutions
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE public.institutions
  ADD COLUMN IF NOT EXISTS disabled_at TIMESTAMPTZ;

ALTER TABLE public.institutions
  ADD COLUMN IF NOT EXISTS disabled_reason TEXT;

-- ---------------------------------------------------------------------------
-- 3. Superadmin audit log — tracks every cross-tenant action
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.superadmin_audit_log (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id      UUID        NOT NULL REFERENCES public.users(id) ON DELETE SET NULL,
  action        TEXT        NOT NULL,          -- e.g. 'DISABLE_INSTITUTION', 'CHANGE_ROLE'
  target_type   TEXT        NOT NULL,          -- 'institution' | 'user' | 'course'
  target_id     UUID,
  payload       JSONB,                         -- before/after snapshot
  ip_address    INET,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_actor      ON public.superadmin_audit_log(actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_target     ON public.superadmin_audit_log(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON public.superadmin_audit_log(created_at DESC);

-- ---------------------------------------------------------------------------
-- 4. Performance indexes for cross-tenant queries (superadmin list views)
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_institutions_is_active  ON public.institutions(is_active);
CREATE INDEX IF NOT EXISTS idx_institutions_created_at ON public.institutions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_users_institution_role  ON public.users(institution_id, role);

-- ---------------------------------------------------------------------------
-- 5. RLS policies — protect direct Supabase dashboard access
--    (Note: backend uses service_role_key which bypasses RLS;
--     these policies protect against direct anon/authenticated key access)
-- ---------------------------------------------------------------------------

-- Superadmin audit log: only superadmins can read
ALTER TABLE public.superadmin_audit_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "superadmin_audit_log_access" ON public.superadmin_audit_log;
CREATE POLICY "superadmin_audit_log_access"
  ON public.superadmin_audit_log
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id   = auth.uid()
        AND role = 'superadmin'
    )
  );

-- Institutions: superadmins can see all; admin/teacher/student only their own
ALTER TABLE public.institutions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "institutions_superadmin"   ON public.institutions;
DROP POLICY IF EXISTS "institutions_own_tenant"   ON public.institutions;

CREATE POLICY "institutions_superadmin"
  ON public.institutions FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id = auth.uid() AND role = 'superadmin'
    )
  );

CREATE POLICY "institutions_own_tenant"
  ON public.institutions FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE id             = auth.uid()
        AND institution_id = institutions.id
    )
  );

-- ---------------------------------------------------------------------------
-- 6. Helper function: is the calling user a superadmin?
--    (Useful for RLS policies on future tables)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'superadmin'
  );
$$;

-- ---------------------------------------------------------------------------
-- Done
-- ---------------------------------------------------------------------------
-- To create a superadmin user after running this migration:
--
--   UPDATE public.users
--   SET    role = 'superadmin'
--   WHERE  email = 'superadmin@captus.dev';
--
-- Make sure the user is registered first via the app or Supabase Auth.
-- =============================================================================
