import pg from 'pg';
import dotenv from 'dotenv';

dotenv.config();

const { Client } = pg;

const setupTables = async () => {
  const connectionString = process.env.DATABASE_URL;

  if (!connectionString) {
    console.error('DATABASE_URL is not defined in .env. Cannot connect to database to create tables.');
    console.log('Please create the following tables manually in your Supabase SQL Editor:');
    console.log(`
      CREATE TABLE IF NOT EXISTS conversations (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id UUID NOT NULL,
        title TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS messages (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);
      CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);
    `);
    process.exit(1);
  }

  const client = new Client({
    connectionString,
    ssl: {
      rejectUnauthorized: false // Supabase requires SSL, but often self-signed in dev or generic
    }
  });

  try {
    await client.connect();
    console.log('Connected to database.');

    await client.query(`
      CREATE TABLE IF NOT EXISTS conversations (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        user_id UUID NOT NULL,
        title TEXT,
        created_at TIMESTAMPTZ DEFAULT NOW(),
        updated_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    console.log('Created conversations table.');

    await client.query(`
      CREATE TABLE IF NOT EXISTS messages (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        conversation_id BIGINT REFERENCES conversations(id) ON DELETE CASCADE,
        role TEXT NOT NULL,
        content TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);
    console.log('Created messages table.');

    await client.query(`CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations(user_id);`);
    await client.query(`CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages(conversation_id);`);
    console.log('Created indices.');

    console.log('Database setup complete.');
  } catch (err) {
    console.error('Error setting up database:', err);
    process.exit(1);
  } finally {
    await client.end();
  }
};

setupTables();
